### ISSUE TITLE
Radiator Wide

### ISSUE THREAD

**Issue by TheNavy** [Wilko01/Radiator_fans#1]
Hello,
I am looking for just such a project. Unfortunately, without printing it, I can't tell how wide the radiator needs to be inside to fit your modules. My German radiators are ~70mm wide inside.

**Comment by TheNavy** [comment]
I have made a test print. It fits ;)

**Comment by Wilko01** [comment]
Hi, 
Sorry for the late response. It is a bit wider than 50mm as the used fans are 50mm and the sides are about 1,x mm. Having 70mm space should always fit. Please let me know if you need the exact details as they are in the drawings, but I don't have my laptop at hand to check.

**Comment by Wilko01** [comment]
provided the necessary information
